# Generated by Django 4.0.3 on 2022-03-20 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='book',
            name='book_isbn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pub_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='data published'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
