# Generated by Django 4.0.3 on 2022-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquote',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookquote',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
