# Generated by Django 4.0.3 on 2022-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookquote_reference_alter_bookquote_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_abstract',
            field=models.TextField(blank=True, default='暂无信息'),
        ),
    ]
