# Generated by Django 4.0.3 on 2022-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_book_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_catalog',
            field=models.TextField(blank=True, default='暂无目录'),
        ),
    ]
