# Generated by Django 4.0.3 on 2022-05-01 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_abstract', models.TextField(blank=True, default='暂无信息')),
                ('movie_type', models.CharField(max_length=50)),
                ('movie_cover', models.CharField(default='', max_length=256)),
                ('movie_director', models.CharField(blank=True, max_length=200)),
                ('movie_screenwriter', models.CharField(blank=True, max_length=200)),
                ('movie_starring', models.CharField(blank=True, max_length=200)),
                ('movie_cr', models.CharField(blank=True, max_length=200)),
                ('movie_pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='data published')),
                ('movie_minutes', models.IntegerField(blank=True)),
                ('movie_episodes', models.IntegerField(blank=True)),
                ('movie_episode_minutes', models.IntegerField(blank=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
